# Generated by Django 5.2.6 on 2025-10-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id_number',
            new_name='student_number',
        ),
    ]
