# Generated by Django 5.2.7 on 2025-10-26 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userlogin_userprofile_delete_profile'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowrecord',
            options={'ordering': ['-borrow_date']},
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userlogin'),
        ),
        migrations.AlterModelTable(
            name='borrowrecord',
            table='borrow_record',
        ),
    ]
