# Generated by Django 5.2.6 on 2025-10-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfos',
            old_name='id_number',
            new_name='student_number',
        ),
    ]
