# Generated by Django 5.2.6 on 2025-10-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_id_number_userinfos_student_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfos',
            name='program',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
